spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

employee-path: localhost:8080/api/employees/

notifications:
  kafka:
    public-topic: employees
    message: Yout position in queue is
office:
  layout-path: office_layout.jpg
  chair-path: src/main/resources/img_templates/

data-initialize:
  path:
    office-options: init_office_options.sql
    reservations: init_reservation.sql
  closed-positions:
    min-position:
      x: 720
      y: 640
    max-position:
      x: 1270



