spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true


employee-path: localhost:8080/api/employees/

notifications:
  kafka:
    public-topic: employees
    message: Yout position ins queue is
