spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true


employee-path: localhost:8080/api/employees/

notifications:
  kafka:
    public-topic: employees
    message: Yout position in queue is
office:
  layout-path: office_layout.jpg
  chair-path: src/main/resources/img_templates
  picture-extension: .jpg

data-initialize:
  path:
    office-options: init_office_options.sql
    reservations: init_reservation.sql
  closed-positions:
    min-position:
      x: 720
      y: 640
    max-position:
      x: 1270



